
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class SubcategoiesTagsEditor
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.Table table1;
		private global::Gtk.CheckButton fastcheckbutton;
		private global::Gtk.Label label1;
		private global::Gtk.CheckButton multicheckbutton;
		private global::Gtk.Entry nameentry;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.VBox tagsbox;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry tagentry;
		private global::Gtk.Button addtagbutton;
		private global::Gtk.Button deletebutton;
		private global::Gtk.Label GtkLabel4;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.SubcategoiesTagsEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.SubcategoiesTagsEditor";
			// Container child LongoMatch.Gui.Component.SubcategoiesTagsEditor.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.fastcheckbutton = new global::Gtk.CheckButton ();
			this.fastcheckbutton.TooltipMarkup = "When this option is selected, the subcategory can be tagged right after creating a new play";
			this.fastcheckbutton.CanFocus = true;
			this.fastcheckbutton.Name = "fastcheckbutton";
			this.fastcheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Quick tag");
			this.fastcheckbutton.Active = true;
			this.fastcheckbutton.DrawIndicator = true;
			this.fastcheckbutton.UseUnderline = true;
			this.table1.Add (this.fastcheckbutton);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.fastcheckbutton]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Subcategory name:");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.multicheckbutton = new global::Gtk.CheckButton ();
			this.multicheckbutton.TooltipMarkup = "This options allows you to select multiple tags instead of just one";
			this.multicheckbutton.CanFocus = true;
			this.multicheckbutton.Name = "multicheckbutton";
			this.multicheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Allow multiple selections");
			this.multicheckbutton.Active = true;
			this.multicheckbutton.DrawIndicator = true;
			this.multicheckbutton.UseUnderline = true;
			this.table1.Add (this.multicheckbutton);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.multicheckbutton]));
			w3.TopAttach = ((uint)(1));
			w3.BottomAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.nameentry = new global::Gtk.Entry ();
			this.nameentry.CanFocus = true;
			this.nameentry.Name = "nameentry";
			this.nameentry.Text = global::Mono.Unix.Catalog.GetString ("Goal type");
			this.nameentry.IsEditable = true;
			this.nameentry.InvisibleChar = '•';
			this.table1.Add (this.nameentry);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.nameentry]));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w6 = new global::Gtk.Viewport ();
			w6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.tagsbox = new global::Gtk.VBox ();
			this.tagsbox.Name = "tagsbox";
			this.tagsbox.Spacing = 6;
			w6.Add (this.tagsbox);
			this.scrolledwindow1.Add (w6);
			this.vbox3.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.scrolledwindow1]));
			w9.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tagentry = new global::Gtk.Entry ();
			this.tagentry.CanFocus = true;
			this.tagentry.Name = "tagentry";
			this.tagentry.Text = global::Mono.Unix.Catalog.GetString ("Penalty");
			this.tagentry.IsEditable = true;
			this.tagentry.InvisibleChar = '•';
			this.hbox1.Add (this.tagentry);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.tagentry]));
			w10.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.addtagbutton = new global::Gtk.Button ();
			this.addtagbutton.CanFocus = true;
			this.addtagbutton.Name = "addtagbutton";
			this.addtagbutton.UseUnderline = true;
			// Container child addtagbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w15.LabelProp = global::Mono.Unix.Catalog.GetString ("Add tag");
			w15.UseUnderline = true;
			w12.Add (w15);
			w11.Add (w12);
			this.addtagbutton.Add (w11);
			this.hbox1.Add (this.addtagbutton);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.addtagbutton]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.deletebutton = new global::Gtk.Button ();
			this.deletebutton.CanFocus = true;
			this.deletebutton.Name = "deletebutton";
			this.deletebutton.UseStock = true;
			this.deletebutton.UseUnderline = true;
			this.deletebutton.Label = "gtk-remove";
			this.vbox3.Add (this.deletebutton);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.deletebutton]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			this.GtkAlignment2.Add (this.vbox3);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Tags</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel4;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
			w24.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
