
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Dialog
{
	public partial class TaggerDialog
	{
		private global::Gtk.VBox mainvbox;
		private global::Gtk.HBox hbox;
		private global::Gtk.Notebook tagsnotebook;
		private global::LongoMatch.Gui.Component.TaggerWidget taggerwidget1;
		private global::Gtk.Label label1;
		private global::Gtk.Notebook playersnotebook;
		private global::Gtk.VBox playersbox;
		private global::Gtk.Label label2;
		private global::Gtk.HBox poshbox;
		private global::LongoMatch.Gui.Component.CoordinatesTagger fieldcoordinatestagger;
		private global::LongoMatch.Gui.Component.CoordinatesTagger halffieldcoordinatestagger;
		private global::LongoMatch.Gui.Component.CoordinatesTagger goalcoordinatestagger;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Dialog.TaggerDialog
			this.Name = "LongoMatch.Gui.Dialog.TaggerDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Tag play");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "longomatch", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child LongoMatch.Gui.Dialog.TaggerDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.mainvbox = new global::Gtk.VBox ();
			this.mainvbox.Name = "mainvbox";
			// Container child mainvbox.Gtk.Box+BoxChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 6;
			// Container child hbox.Gtk.Box+BoxChild
			this.tagsnotebook = new global::Gtk.Notebook ();
			this.tagsnotebook.CanFocus = true;
			this.tagsnotebook.Name = "tagsnotebook";
			this.tagsnotebook.CurrentPage = 0;
			// Container child tagsnotebook.Gtk.Notebook+NotebookChild
			this.taggerwidget1 = new global::LongoMatch.Gui.Component.TaggerWidget ();
			this.taggerwidget1.Events = ((global::Gdk.EventMask)(256));
			this.taggerwidget1.Name = "taggerwidget1";
			this.tagsnotebook.Add (this.taggerwidget1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Tags");
			this.tagsnotebook.SetTabLabel (this.taggerwidget1, this.label1);
			this.label1.ShowAll ();
			this.hbox.Add (this.tagsnotebook);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox [this.tagsnotebook]));
			w3.Position = 0;
			// Container child hbox.Gtk.Box+BoxChild
			this.playersnotebook = new global::Gtk.Notebook ();
			this.playersnotebook.CanFocus = true;
			this.playersnotebook.Name = "playersnotebook";
			this.playersnotebook.CurrentPage = 0;
			// Container child playersnotebook.Gtk.Notebook+NotebookChild
			this.playersbox = new global::Gtk.VBox ();
			this.playersbox.Name = "playersbox";
			this.playersbox.Spacing = 6;
			this.playersnotebook.Add (this.playersbox);
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Players");
			this.playersnotebook.SetTabLabel (this.playersbox, this.label2);
			this.label2.ShowAll ();
			this.hbox.Add (this.playersnotebook);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox [this.playersnotebook]));
			w5.Position = 1;
			this.mainvbox.Add (this.hbox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.mainvbox [this.hbox]));
			w6.Position = 0;
			w6.Expand = false;
			// Container child mainvbox.Gtk.Box+BoxChild
			this.poshbox = new global::Gtk.HBox ();
			this.poshbox.Name = "poshbox";
			// Container child poshbox.Gtk.Box+BoxChild
			this.fieldcoordinatestagger = new global::LongoMatch.Gui.Component.CoordinatesTagger ();
			this.fieldcoordinatestagger.Events = ((global::Gdk.EventMask)(256));
			this.fieldcoordinatestagger.Name = "fieldcoordinatestagger";
			this.poshbox.Add (this.fieldcoordinatestagger);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.poshbox [this.fieldcoordinatestagger]));
			w7.Position = 0;
			// Container child poshbox.Gtk.Box+BoxChild
			this.halffieldcoordinatestagger = new global::LongoMatch.Gui.Component.CoordinatesTagger ();
			this.halffieldcoordinatestagger.Events = ((global::Gdk.EventMask)(256));
			this.halffieldcoordinatestagger.Name = "halffieldcoordinatestagger";
			this.poshbox.Add (this.halffieldcoordinatestagger);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.poshbox [this.halffieldcoordinatestagger]));
			w8.Position = 1;
			// Container child poshbox.Gtk.Box+BoxChild
			this.goalcoordinatestagger = new global::LongoMatch.Gui.Component.CoordinatesTagger ();
			this.goalcoordinatestagger.Events = ((global::Gdk.EventMask)(256));
			this.goalcoordinatestagger.Name = "goalcoordinatestagger";
			this.poshbox.Add (this.goalcoordinatestagger);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.poshbox [this.goalcoordinatestagger]));
			w9.Position = 2;
			this.mainvbox.Add (this.poshbox);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.mainvbox [this.poshbox]));
			w10.Position = 1;
			w1.Add (this.mainvbox);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.mainvbox]));
			w11.Position = 0;
			// Internal child LongoMatch.Gui.Dialog.TaggerDialog.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 6;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonOk]));
			w13.Expand = false;
			w13.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 644;
			this.DefaultHeight = 569;
			this.fieldcoordinatestagger.Hide ();
			this.halffieldcoordinatestagger.Hide ();
			this.goalcoordinatestagger.Hide ();
			this.Show ();
		}
	}
}
