
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component.Stats
{
	public partial class CategoryViewer
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.VBox vbox1;
		private global::LongoMatch.Gui.Component.PlaysCoordinatesTagger playscoordinatestagger1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.Stats.CategoryViewer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.Stats.CategoryViewer";
			// Container child LongoMatch.Gui.Component.Stats.CategoryViewer.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.playscoordinatestagger1 = new global::LongoMatch.Gui.Component.PlaysCoordinatesTagger ();
			this.playscoordinatestagger1.Events = ((global::Gdk.EventMask)(256));
			this.playscoordinatestagger1.Name = "playscoordinatestagger1";
			this.vbox1.Add (this.playscoordinatestagger1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.playscoordinatestagger1]));
			w2.Position = 1;
			w1.Add (this.vbox1);
			this.scrolledwindow1.Add (w1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
