
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class GameViewer
	{
		private global::Gtk.VBox mainbox;
		private global::Gtk.HBox topbox;
		private global::Gtk.Image homeimage;
		private global::Gtk.Label homelabel;
		private global::Gtk.CheckButton subcatscheckbutton;
		private global::Gtk.Label awaylabel;
		private global::Gtk.Image awayimage;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.VBox cstatsbox;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.GameViewer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.GameViewer";
			// Container child LongoMatch.Gui.Component.GameViewer.Gtk.Container+ContainerChild
			this.mainbox = new global::Gtk.VBox ();
			this.mainbox.Name = "mainbox";
			this.mainbox.Spacing = 6;
			// Container child mainbox.Gtk.Box+BoxChild
			this.topbox = new global::Gtk.HBox ();
			this.topbox.Name = "topbox";
			this.topbox.Homogeneous = true;
			this.topbox.Spacing = 6;
			// Container child topbox.Gtk.Box+BoxChild
			this.homeimage = new global::Gtk.Image ();
			this.homeimage.Name = "homeimage";
			this.topbox.Add (this.homeimage);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.topbox [this.homeimage]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child topbox.Gtk.Box+BoxChild
			this.homelabel = new global::Gtk.Label ();
			this.homelabel.Name = "homelabel";
			this.topbox.Add (this.homelabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.topbox [this.homelabel]));
			w2.Position = 1;
			w2.Fill = false;
			// Container child topbox.Gtk.Box+BoxChild
			this.subcatscheckbutton = new global::Gtk.CheckButton ();
			this.subcatscheckbutton.CanFocus = true;
			this.subcatscheckbutton.Name = "subcatscheckbutton";
			this.subcatscheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Sub categories");
			this.subcatscheckbutton.DrawIndicator = true;
			this.subcatscheckbutton.UseUnderline = true;
			this.topbox.Add (this.subcatscheckbutton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.topbox [this.subcatscheckbutton]));
			w3.Position = 2;
			// Container child topbox.Gtk.Box+BoxChild
			this.awaylabel = new global::Gtk.Label ();
			this.awaylabel.Name = "awaylabel";
			this.topbox.Add (this.awaylabel);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.topbox [this.awaylabel]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child topbox.Gtk.Box+BoxChild
			this.awayimage = new global::Gtk.Image ();
			this.awayimage.Name = "awayimage";
			this.topbox.Add (this.awayimage);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.topbox [this.awayimage]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.mainbox.Add (this.topbox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.mainbox [this.topbox]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child mainbox.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w7 = new global::Gtk.Viewport ();
			w7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.cstatsbox = new global::Gtk.VBox ();
			this.cstatsbox.Name = "cstatsbox";
			this.cstatsbox.Spacing = 2;
			w7.Add (this.cstatsbox);
			this.scrolledwindow1.Add (w7);
			this.mainbox.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.mainbox [this.scrolledwindow1]));
			w10.Position = 1;
			this.Add (this.mainbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.subcatscheckbutton.Clicked += new global::System.EventHandler (this.OnSubcatscheckbuttonClicked);
		}
	}
}
