
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class AnalysisComponent
	{
		private global::Gtk.HPaned hpaned;
		private global::Gtk.VBox leftbox;
		private global::LongoMatch.Gui.Component.PlaysSelectionWidget playsSelection;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.VBox downbox;
		private global::Gtk.HBox videowidgetsbox;
		private global::LongoMatch.Gui.Component.DrawingToolBox drawingtoolbox1;
		private global::LongoMatch.Gui.PlayerCapturerBin playercapturer;
		private global::LongoMatch.Gui.Component.ButtonsWidget buttonswidget;
		private global::LongoMatch.Gui.Component.GameUnitsTagger gameunitstaggerwidget1;
		private global::Gtk.HBox righthbox;
		private global::Gtk.VBox tagsvbox;
		private global::LongoMatch.Gui.Component.PlaysCoordinatesTagger postagger;
		private global::Gtk.Frame notesframe;
		private global::Gtk.Alignment GtkAlignment22;
		private global::LongoMatch.Gui.Component.NotesWidget notes;
		private global::Gtk.Label GtkLabel31;
		private global::LongoMatch.Gui.Component.PlayListWidget playlist;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.AnalysisComponent
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.AnalysisComponent";
			// Container child LongoMatch.Gui.Component.AnalysisComponent.Gtk.Container+ContainerChild
			this.hpaned = new global::Gtk.HPaned ();
			this.hpaned.CanFocus = true;
			this.hpaned.Name = "hpaned";
			this.hpaned.Position = 233;
			// Container child hpaned.Gtk.Paned+PanedChild
			this.leftbox = new global::Gtk.VBox ();
			this.leftbox.Name = "leftbox";
			this.leftbox.Spacing = 6;
			// Container child leftbox.Gtk.Box+BoxChild
			this.playsSelection = new global::LongoMatch.Gui.Component.PlaysSelectionWidget ();
			this.playsSelection.Events = ((global::Gdk.EventMask)(256));
			this.playsSelection.Name = "playsSelection";
			this.leftbox.Add (this.playsSelection);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.leftbox [this.playsSelection]));
			w1.Position = 0;
			this.hpaned.Add (this.leftbox);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned [this.leftbox]));
			w2.Resize = false;
			// Container child hpaned.Gtk.Paned+PanedChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 1160;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.downbox = new global::Gtk.VBox ();
			this.downbox.Name = "downbox";
			this.downbox.Spacing = 6;
			// Container child downbox.Gtk.Box+BoxChild
			this.videowidgetsbox = new global::Gtk.HBox ();
			this.videowidgetsbox.Name = "videowidgetsbox";
			this.videowidgetsbox.Spacing = 6;
			// Container child videowidgetsbox.Gtk.Box+BoxChild
			this.drawingtoolbox1 = new global::LongoMatch.Gui.Component.DrawingToolBox ();
			this.drawingtoolbox1.Events = ((global::Gdk.EventMask)(256));
			this.drawingtoolbox1.Name = "drawingtoolbox1";
			this.videowidgetsbox.Add (this.drawingtoolbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.videowidgetsbox [this.drawingtoolbox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child videowidgetsbox.Gtk.Box+BoxChild
			this.playercapturer = new global::LongoMatch.Gui.PlayerCapturerBin ();
			this.playercapturer.Events = ((global::Gdk.EventMask)(256));
			this.playercapturer.Name = "playercapturer";
			this.playercapturer.Detached = false;
			this.playercapturer.ExpandLogo = false;
			this.playercapturer.Rate = 0F;
			this.videowidgetsbox.Add (this.playercapturer);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.videowidgetsbox [this.playercapturer]));
			w4.Position = 1;
			this.downbox.Add (this.videowidgetsbox);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.downbox [this.videowidgetsbox]));
			w5.Position = 0;
			// Container child downbox.Gtk.Box+BoxChild
			this.buttonswidget = new global::LongoMatch.Gui.Component.ButtonsWidget ();
			this.buttonswidget.Events = ((global::Gdk.EventMask)(256));
			this.buttonswidget.Name = "buttonswidget";
			this.downbox.Add (this.buttonswidget);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.downbox [this.buttonswidget]));
			w6.Position = 1;
			w6.Expand = false;
			// Container child downbox.Gtk.Box+BoxChild
			this.gameunitstaggerwidget1 = new global::LongoMatch.Gui.Component.GameUnitsTagger ();
			this.gameunitstaggerwidget1.Events = ((global::Gdk.EventMask)(256));
			this.gameunitstaggerwidget1.Name = "gameunitstaggerwidget1";
			this.downbox.Add (this.gameunitstaggerwidget1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.downbox [this.gameunitstaggerwidget1]));
			w7.Position = 2;
			w7.Expand = false;
			this.hpaned1.Add (this.downbox);
			global::Gtk.Paned.PanedChild w8 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.downbox]));
			w8.Resize = false;
			w8.Shrink = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.righthbox = new global::Gtk.HBox ();
			this.righthbox.WidthRequest = 100;
			this.righthbox.Name = "righthbox";
			this.righthbox.Spacing = 6;
			// Container child righthbox.Gtk.Box+BoxChild
			this.tagsvbox = new global::Gtk.VBox ();
			this.tagsvbox.WidthRequest = 100;
			this.tagsvbox.Name = "tagsvbox";
			this.tagsvbox.Spacing = 6;
			// Container child tagsvbox.Gtk.Box+BoxChild
			this.postagger = new global::LongoMatch.Gui.Component.PlaysCoordinatesTagger ();
			this.postagger.Events = ((global::Gdk.EventMask)(256));
			this.postagger.Name = "postagger";
			this.tagsvbox.Add (this.postagger);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.tagsvbox [this.postagger]));
			w9.Position = 0;
			// Container child tagsvbox.Gtk.Box+BoxChild
			this.notesframe = new global::Gtk.Frame ();
			this.notesframe.Name = "notesframe";
			this.notesframe.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child notesframe.Gtk.Container+ContainerChild
			this.GtkAlignment22 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment22.Name = "GtkAlignment22";
			this.GtkAlignment22.LeftPadding = ((uint)(12));
			// Container child GtkAlignment22.Gtk.Container+ContainerChild
			this.notes = new global::LongoMatch.Gui.Component.NotesWidget ();
			this.notes.Events = ((global::Gdk.EventMask)(256));
			this.notes.Name = "notes";
			this.GtkAlignment22.Add (this.notes);
			this.notesframe.Add (this.GtkAlignment22);
			this.GtkLabel31 = new global::Gtk.Label ();
			this.GtkLabel31.Name = "GtkLabel31";
			this.GtkLabel31.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Notes</b>");
			this.GtkLabel31.UseMarkup = true;
			this.notesframe.LabelWidget = this.GtkLabel31;
			this.tagsvbox.Add (this.notesframe);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.tagsvbox [this.notesframe]));
			w12.Position = 1;
			this.righthbox.Add (this.tagsvbox);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.righthbox [this.tagsvbox]));
			w13.Position = 0;
			// Container child righthbox.Gtk.Box+BoxChild
			this.playlist = new global::LongoMatch.Gui.Component.PlayListWidget ();
			this.playlist.WidthRequest = 100;
			this.playlist.Events = ((global::Gdk.EventMask)(256));
			this.playlist.Name = "playlist";
			this.righthbox.Add (this.playlist);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.righthbox [this.playlist]));
			w14.Position = 1;
			this.hpaned1.Add (this.righthbox);
			global::Gtk.Paned.PanedChild w15 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.righthbox]));
			w15.Resize = false;
			w15.Shrink = false;
			this.hpaned.Add (this.hpaned1);
			global::Gtk.Paned.PanedChild w16 = ((global::Gtk.Paned.PanedChild)(this.hpaned [this.hpaned1]));
			w16.Shrink = false;
			this.Add (this.hpaned);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.leftbox.Hide ();
			this.drawingtoolbox1.Hide ();
			this.buttonswidget.Hide ();
			this.tagsvbox.Hide ();
			this.playlist.Hide ();
			this.righthbox.Hide ();
			this.Hide ();
		}
	}
}
