
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component.Stats
{
	public partial class CategoriesViewer
	{
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeview;
		private global::Gtk.ScrolledWindow scrolledwindow3;
		private global::LongoMatch.Gui.Component.Stats.CategoryViewer categoryviewer1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.Stats.CategoriesViewer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.Stats.CategoriesViewer";
			// Container child LongoMatch.Gui.Component.Stats.CategoriesViewer.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 185;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview = new global::Gtk.TreeView ();
			this.treeview.CanFocus = true;
			this.treeview.Name = "treeview";
			this.GtkScrolledWindow.Add (this.treeview);
			this.hpaned1.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow]));
			w2.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.categoryviewer1 = new global::LongoMatch.Gui.Component.Stats.CategoryViewer ();
			this.categoryviewer1.Events = ((global::Gdk.EventMask)(256));
			this.categoryviewer1.Name = "categoryviewer1";
			w3.Add (this.categoryviewer1);
			this.scrolledwindow3.Add (w3);
			this.hpaned1.Add (this.scrolledwindow3);
			this.Add (this.hpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
