
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Dialog
{
	public partial class ProjectsManager
	{
		private global::Gtk.VBox dialog1_VBox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.HPaned hpaned1;
		private global::LongoMatch.Gui.Component.ProjectListWidget projectlistwidget1;
		private global::Gtk.ScrolledWindow scrolledwindow3;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment2;
		private global::LongoMatch.Gui.Component.ProjectDetailsWidget projectdetails;
		private global::Gtk.Label GtkLabel7;
		private global::Gtk.Button saveButton;
		private global::Gtk.Button deleteButton;
		private global::Gtk.Button exportbutton;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Dialog.ProjectsManager
			this.Name = "LongoMatch.Gui.Dialog.ProjectsManager";
			this.Title = global::Mono.Unix.Catalog.GetString ("Projects Manager");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "longomatch", global::Gtk.IconSize.Dialog);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child LongoMatch.Gui.Dialog.ProjectsManager.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.dialog1_VBox1 = new global::Gtk.VBox ();
			this.dialog1_VBox1.Name = "dialog1_VBox1";
			this.dialog1_VBox1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 349;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.projectlistwidget1 = new global::LongoMatch.Gui.Component.ProjectListWidget ();
			this.projectlistwidget1.Events = ((global::Gdk.EventMask)(256));
			this.projectlistwidget1.Name = "projectlistwidget1";
			this.hpaned1.Add (this.projectlistwidget1);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.projectlistwidget1]));
			w2.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport ();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.projectdetails = new global::LongoMatch.Gui.Component.ProjectDetailsWidget ();
			this.projectdetails.Sensitive = false;
			this.projectdetails.Events = ((global::Gdk.EventMask)(256));
			this.projectdetails.Name = "projectdetails";
			this.projectdetails.Edited = false;
			this.projectdetails.LocalGoals = 0;
			this.projectdetails.VisitorGoals = 0;
			this.projectdetails.Date = new global::System.DateTime (0);
			this.GtkAlignment2.Add (this.projectdetails);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Project Details</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel7;
			this.vbox3.Add (this.frame1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame1]));
			w6.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.saveButton = new global::Gtk.Button ();
			this.saveButton.TooltipMarkup = "Save the selected project";
			this.saveButton.Sensitive = false;
			this.saveButton.CanFocus = true;
			this.saveButton.Name = "saveButton";
			this.saveButton.UseStock = true;
			this.saveButton.UseUnderline = true;
			this.saveButton.Label = "gtk-save";
			this.vbox3.Add (this.saveButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.saveButton]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.deleteButton = new global::Gtk.Button ();
			this.deleteButton.TooltipMarkup = "Delete the selected project";
			this.deleteButton.Sensitive = false;
			this.deleteButton.CanFocus = true;
			this.deleteButton.Name = "deleteButton";
			this.deleteButton.UseStock = true;
			this.deleteButton.UseUnderline = true;
			this.deleteButton.Label = "gtk-delete";
			this.vbox3.Add (this.deleteButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.deleteButton]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.exportbutton = new global::Gtk.Button ();
			this.exportbutton.TooltipMarkup = "Export the selected project to a file";
			this.exportbutton.Sensitive = false;
			this.exportbutton.CanFocus = true;
			this.exportbutton.Name = "exportbutton";
			this.exportbutton.UseUnderline = true;
			// Container child exportbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w9 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w10 = new global::Gtk.HBox ();
			w10.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w11 = new global::Gtk.Image ();
			w11.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_export", global::Gtk.IconSize.Menu);
			w10.Add (w11);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w13 = new global::Gtk.Label ();
			w13.LabelProp = global::Mono.Unix.Catalog.GetString ("_Export");
			w13.UseUnderline = true;
			w10.Add (w13);
			w9.Add (w10);
			this.exportbutton.Add (w9);
			this.vbox3.Add (this.exportbutton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.exportbutton]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			w3.Add (this.vbox3);
			this.scrolledwindow3.Add (w3);
			this.hpaned1.Add (this.scrolledwindow3);
			this.hbox2.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hpaned1]));
			w21.Position = 0;
			this.dialog1_VBox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox1 [this.hbox2]));
			w22.Position = 0;
			// Container child dialog1_VBox1.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.dialog1_VBox1.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox1 [this.hseparator3]));
			w23.PackType = ((global::Gtk.PackType)(1));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			w1.Add (this.dialog1_VBox1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(w1 [this.dialog1_VBox1]));
			w24.Position = 0;
			// Internal child LongoMatch.Gui.Dialog.ProjectsManager.ActionArea
			global::Gtk.HButtonBox w25 = this.ActionArea;
			w25.Name = "dialog1_ActionArea";
			w25.Spacing = 6;
			w25.BorderWidth = ((uint)(5));
			w25.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-quit";
			this.AddActionWidget (this.buttonOk, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w25 [this.buttonOk]));
			w26.Expand = false;
			w26.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 833;
			this.DefaultHeight = 538;
			this.Show ();
			this.projectlistwidget1.ProjectsSelected += new global::LongoMatch.Handlers.ProjectsSelectedHandler (this.OnProjectlistwidget1ProjectsSelected);
			this.projectdetails.EditedEvent += new global::System.EventHandler (this.OnProjectdetailsEditedEvent);
			this.saveButton.Pressed += new global::System.EventHandler (this.OnSaveButtonPressed);
			this.deleteButton.Pressed += new global::System.EventHandler (this.OnDeleteButtonPressed);
			this.exportbutton.Clicked += new global::System.EventHandler (this.OnExportbuttonClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
