
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component.Stats
{
	public partial class Plotter
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.RadioButton historadiobutton;
		private global::Gtk.RadioButton pieradiobutton;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Image imageall;
		private global::Gtk.Image imagehome;
		private global::Gtk.Image imageaway;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.Stats.Plotter
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.Stats.Plotter";
			// Container child LongoMatch.Gui.Component.Stats.Plotter.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.historadiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Histogram"));
			this.historadiobutton.CanFocus = true;
			this.historadiobutton.Name = "historadiobutton";
			this.historadiobutton.DrawIndicator = true;
			this.historadiobutton.UseUnderline = true;
			this.historadiobutton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox4.Add (this.historadiobutton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.historadiobutton]));
			w1.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.pieradiobutton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Pie chart"));
			this.pieradiobutton.CanFocus = true;
			this.pieradiobutton.Name = "pieradiobutton";
			this.pieradiobutton.DrawIndicator = true;
			this.pieradiobutton.UseUnderline = true;
			this.pieradiobutton.Group = this.historadiobutton.Group;
			this.hbox4.Add (this.pieradiobutton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.pieradiobutton]));
			w2.Position = 1;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.imageall = new global::Gtk.Image ();
			this.imageall.Name = "imageall";
			this.hbox3.Add (this.imageall);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.imageall]));
			w4.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.imagehome = new global::Gtk.Image ();
			this.imagehome.Name = "imagehome";
			this.hbox3.Add (this.imagehome);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.imagehome]));
			w5.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.imageaway = new global::Gtk.Image ();
			this.imageaway.Name = "imageaway";
			this.hbox3.Add (this.imageaway);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.imageaway]));
			w6.Position = 2;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w7.Position = 1;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
