
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class PlaysCoordinatesTagger
	{
		private global::Gtk.VBox mainbox;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.PlaysCoordinatesTagger
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.PlaysCoordinatesTagger";
			// Container child LongoMatch.Gui.Component.PlaysCoordinatesTagger.Gtk.Container+ContainerChild
			this.mainbox = new global::Gtk.VBox ();
			this.mainbox.Name = "mainbox";
			this.mainbox.Spacing = 6;
			this.Add (this.mainbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
