
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Dialog
{
	public partial class VideoEditionProperties
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label1;
		private global::Gtk.ComboBox qualitycombobox;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label2;
		private global::Gtk.ComboBox sizecombobox;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label label3;
		private global::Gtk.ComboBox formatcombobox;
		private global::Gtk.HBox hbox6;
		private global::Gtk.CheckButton descriptioncheckbutton;
		private global::Gtk.CheckButton audiocheckbutton;
		private global::Gtk.CheckButton splitfilesbutton;
		private global::Gtk.HBox filebox;
		private global::Gtk.Label filenamelabel;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label filelabel;
		private global::Gtk.Button openbutton;
		private global::Gtk.HBox dirbox;
		private global::Gtk.Label directorynamelabel1;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label dirlabel;
		private global::Gtk.Button opendirbutton;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Dialog.VideoEditionProperties
			this.Name = "LongoMatch.Gui.Dialog.VideoEditionProperties";
			this.Title = global::Mono.Unix.Catalog.GetString ("Video Properties");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "longomatch", global::Gtk.IconSize.Dialog);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child LongoMatch.Gui.Dialog.VideoEditionProperties.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Video Quality:");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.qualitycombobox = global::Gtk.ComboBox.NewText ();
			this.qualitycombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Low"));
			this.qualitycombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Normal"));
			this.qualitycombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Good"));
			this.qualitycombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Extra"));
			this.qualitycombobox.Name = "qualitycombobox";
			this.qualitycombobox.Active = 1;
			this.hbox2.Add (this.qualitycombobox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.qualitycombobox]));
			w3.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Size: ");
			this.hbox4.Add (this.label2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
			w5.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.sizecombobox = global::Gtk.ComboBox.NewText ();
			this.sizecombobox.Name = "sizecombobox";
			this.hbox4.Add (this.sizecombobox);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.sizecombobox]));
			w6.Position = 1;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Homogeneous = true;
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Ouput Format:");
			this.hbox5.Add (this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label3]));
			w8.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.formatcombobox = global::Gtk.ComboBox.NewText ();
			this.formatcombobox.Name = "formatcombobox";
			this.hbox5.Add (this.formatcombobox);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.formatcombobox]));
			w9.Position = 1;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.descriptioncheckbutton = new global::Gtk.CheckButton ();
			this.descriptioncheckbutton.CanFocus = true;
			this.descriptioncheckbutton.Name = "descriptioncheckbutton";
			this.descriptioncheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Enable Title Overlay");
			this.descriptioncheckbutton.Active = true;
			this.descriptioncheckbutton.DrawIndicator = true;
			this.descriptioncheckbutton.UseUnderline = true;
			this.hbox6.Add (this.descriptioncheckbutton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.descriptioncheckbutton]));
			w11.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.audiocheckbutton = new global::Gtk.CheckButton ();
			this.audiocheckbutton.CanFocus = true;
			this.audiocheckbutton.Name = "audiocheckbutton";
			this.audiocheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Enable Audio (Experimental)");
			this.audiocheckbutton.DrawIndicator = true;
			this.audiocheckbutton.UseUnderline = true;
			this.hbox6.Add (this.audiocheckbutton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.audiocheckbutton]));
			w12.Position = 1;
			this.vbox2.Add (this.hbox6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.splitfilesbutton = new global::Gtk.CheckButton ();
			this.splitfilesbutton.CanFocus = true;
			this.splitfilesbutton.Name = "splitfilesbutton";
			this.splitfilesbutton.Label = global::Mono.Unix.Catalog.GetString ("Split output in one file per playlist element");
			this.splitfilesbutton.DrawIndicator = true;
			this.splitfilesbutton.UseUnderline = true;
			this.vbox2.Add (this.splitfilesbutton);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.splitfilesbutton]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.filebox = new global::Gtk.HBox ();
			this.filebox.Name = "filebox";
			this.filebox.Spacing = 6;
			// Container child filebox.Gtk.Box+BoxChild
			this.filenamelabel = new global::Gtk.Label ();
			this.filenamelabel.Name = "filenamelabel";
			this.filenamelabel.LabelProp = global::Mono.Unix.Catalog.GetString ("File name: ");
			this.filebox.Add (this.filenamelabel);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.filebox [this.filenamelabel]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child filebox.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.filelabel = new global::Gtk.Label ();
			this.filelabel.Name = "filelabel";
			this.hbox3.Add (this.filelabel);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.filelabel]));
			w16.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.openbutton = new global::Gtk.Button ();
			this.openbutton.CanFocus = true;
			this.openbutton.Name = "openbutton";
			this.openbutton.UseStock = true;
			this.openbutton.UseUnderline = true;
			this.openbutton.Label = "gtk-save-as";
			this.hbox3.Add (this.openbutton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.openbutton]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.filebox.Add (this.hbox3);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.filebox [this.hbox3]));
			w18.Position = 1;
			this.vbox2.Add (this.filebox);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.filebox]));
			w19.Position = 5;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.dirbox = new global::Gtk.HBox ();
			this.dirbox.Name = "dirbox";
			this.dirbox.Spacing = 6;
			// Container child dirbox.Gtk.Box+BoxChild
			this.directorynamelabel1 = new global::Gtk.Label ();
			this.directorynamelabel1.Name = "directorynamelabel1";
			this.directorynamelabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Directory name: ");
			this.dirbox.Add (this.directorynamelabel1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.dirbox [this.directorynamelabel1]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child dirbox.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.dirlabel = new global::Gtk.Label ();
			this.dirlabel.Name = "dirlabel";
			this.hbox8.Add (this.dirlabel);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.dirlabel]));
			w21.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.opendirbutton = new global::Gtk.Button ();
			this.opendirbutton.CanFocus = true;
			this.opendirbutton.Name = "opendirbutton";
			this.opendirbutton.UseStock = true;
			this.opendirbutton.UseUnderline = true;
			this.opendirbutton.Label = "gtk-save-as";
			this.hbox8.Add (this.opendirbutton);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.opendirbutton]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.dirbox.Add (this.hbox8);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.dirbox [this.hbox8]));
			w23.Position = 1;
			this.vbox2.Add (this.dirbox);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.dirbox]));
			w24.Position = 6;
			w24.Expand = false;
			w24.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Internal child LongoMatch.Gui.Dialog.VideoEditionProperties.ActionArea
			global::Gtk.HButtonBox w26 = this.ActionArea;
			w26.Name = "dialog1_ActionArea";
			w26.Spacing = 6;
			w26.BorderWidth = ((uint)(5));
			w26.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26 [this.buttonCancel]));
			w27.Expand = false;
			w27.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w28 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26 [this.buttonOk]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 516;
			this.DefaultHeight = 309;
			this.dirbox.Hide ();
			this.Show ();
			this.splitfilesbutton.Clicked += new global::System.EventHandler (this.OnSplitfilesbuttonClicked);
			this.openbutton.Clicked += new global::System.EventHandler (this.OnOpenbuttonClicked);
			this.opendirbutton.Clicked += new global::System.EventHandler (this.OnOpendirbuttonClicked);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
