
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class TaggerWidget
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.HBox hbox2;
		private global::Gtk.CheckButton localcheckbutton;
		private global::Gtk.CheckButton visitorcheckbutton;
		private global::Gtk.Label GtkLabel2;
		private global::Gtk.Frame periodframe;
		private global::Gtk.Alignment GtkAlignment1;
		private global::Gtk.HBox periodhbox;
		private global::Gtk.Label PeriodLabel;
		private global::Gtk.Table table1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.TaggerWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.TaggerWidget";
			// Container child LongoMatch.Gui.Component.TaggerWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.localcheckbutton = new global::Gtk.CheckButton ();
			this.localcheckbutton.CanFocus = true;
			this.localcheckbutton.Name = "localcheckbutton";
			this.localcheckbutton.Label = "";
			this.localcheckbutton.DrawIndicator = true;
			this.localcheckbutton.UseUnderline = true;
			this.hbox2.Add (this.localcheckbutton);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.localcheckbutton]));
			w1.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.visitorcheckbutton = new global::Gtk.CheckButton ();
			this.visitorcheckbutton.CanFocus = true;
			this.visitorcheckbutton.Name = "visitorcheckbutton";
			this.visitorcheckbutton.Label = "";
			this.visitorcheckbutton.DrawIndicator = true;
			this.visitorcheckbutton.UseUnderline = true;
			this.hbox2.Add (this.visitorcheckbutton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.visitorcheckbutton]));
			w2.Position = 1;
			this.GtkAlignment.Add (this.hbox2);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Team</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.hbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame1]));
			w5.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.periodframe = new global::Gtk.Frame ();
			this.periodframe.Name = "periodframe";
			this.periodframe.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child periodframe.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.periodhbox = new global::Gtk.HBox ();
			this.periodhbox.Name = "periodhbox";
			this.periodhbox.Spacing = 6;
			this.GtkAlignment1.Add (this.periodhbox);
			this.periodframe.Add (this.GtkAlignment1);
			this.PeriodLabel = new global::Gtk.Label ();
			this.PeriodLabel.Name = "PeriodLabel";
			this.PeriodLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Period</b>");
			this.PeriodLabel.UseMarkup = true;
			this.periodframe.LabelWidget = this.PeriodLabel;
			this.hbox1.Add (this.periodframe);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.periodframe]));
			w8.Position = 1;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.vbox3.Add (this.table1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table1]));
			w10.Position = 1;
			w10.Expand = false;
			this.vbox2.Add (this.vbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.vbox3]));
			w11.Position = 0;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
